package transporters

import (
	"context"

	"github.com/Moreira-Henrique-Pedro/entregador/internal/domain/interfaces/pubsub"
	"github.com/google/uuid"
)

// commandIDNamespace scopes the UUIDv5 command ids generated by this service.
var commandIDNamespace = uuid.MustParse("6f1c2a4e-3b8d-4c5e-9a7f-2d1e0b9c8a76")

// newCommandID derives the command id from the source message, so a redelivered
// event produces the same command and the writers deduplicate it by id.
func newCommandID(ctx context.Context) string {
	if sourceID, ok := pubsub.SourceMessageIDFromContext(ctx); ok {
		return uuid.NewSHA1(commandIDNamespace, []byte(sourceID)).String()
	}
	return uuid.New().String()
}
