// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TwilioClientPort is an autogenerated mock type for the TwilioClientPort type
type TwilioClientPort struct {
	mock.Mock
}

// SendWhatsAppMessage provides a mock function with given fields: ctx, to, message
func (_m *TwilioClientPort) SendWhatsAppMessage(ctx context.Context, to string, message string) error {
	ret := _m.Called(ctx, to, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTwilioClientPort interface {
	mock.TestingT
	Cleanup(func())
}

// NewTwilioClientPort creates a new instance of TwilioClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTwilioClientPort(t mockConstructorTestingTNewTwilioClientPort) *TwilioClientPort {
	mock := &TwilioClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
