// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TwilioPort is an autogenerated mock type for the TwilioPort type
type TwilioPort struct {
	mock.Mock
}

// SendWhatsAppMessage provides a mock function with given fields: ctx, to
func (_m *TwilioPort) SendWhatsAppMessage(ctx context.Context, to string) error {
	ret := _m.Called(ctx, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTwilioPort interface {
	mock.TestingT
	Cleanup(func())
}

// NewTwilioPort creates a new instance of TwilioPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTwilioPort(t mockConstructorTestingTNewTwilioPort) *TwilioPort {
	mock := &TwilioPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
