// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// DeliveryRepositoryPort is an autogenerated mock type for the DeliveryRepositoryPort type
type DeliveryRepositoryPort struct {
	mock.Mock
}

type DeliveryRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *DeliveryRepositoryPort) EXPECT() *DeliveryRepositoryPort_Expecter {
	return &DeliveryRepositoryPort_Expecter{mock: &_m.Mock}
}

// FindByApartment provides a mock function with given fields: ctx, apartment, status
func (_m *DeliveryRepositoryPort) FindByApartment(ctx context.Context, apartment string, status *entities.DeliveryStatus) ([]*entities.Delivery, error) {
	ret := _m.Called(ctx, apartment, status)

	if len(ret) == 0 {
		panic("no return value specified for FindByApartment")
	}

	var r0 []*entities.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.DeliveryStatus) ([]*entities.Delivery, error)); ok {
		return rf(ctx, apartment, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.DeliveryStatus) []*entities.Delivery); ok {
		r0 = rf(ctx, apartment, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *entities.DeliveryStatus) error); ok {
		r1 = rf(ctx, apartment, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeliveryRepositoryPort_FindByApartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByApartment'
type DeliveryRepositoryPort_FindByApartment_Call struct {
	*mock.Call
}

// FindByApartment is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
//   - status *entities.DeliveryStatus
func (_e *DeliveryRepositoryPort_Expecter) FindByApartment(ctx interface{}, apartment interface{}, status interface{}) *DeliveryRepositoryPort_FindByApartment_Call {
	return &DeliveryRepositoryPort_FindByApartment_Call{Call: _e.mock.On("FindByApartment", ctx, apartment, status)}
}

func (_c *DeliveryRepositoryPort_FindByApartment_Call) Run(run func(ctx context.Context, apartment string, status *entities.DeliveryStatus)) *DeliveryRepositoryPort_FindByApartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*entities.DeliveryStatus))
	})
	return _c
}

func (_c *DeliveryRepositoryPort_FindByApartment_Call) Return(_a0 []*entities.Delivery, _a1 error) *DeliveryRepositoryPort_FindByApartment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeliveryRepositoryPort_FindByApartment_Call) RunAndReturn(run func(context.Context, string, *entities.DeliveryStatus) ([]*entities.Delivery, error)) *DeliveryRepositoryPort_FindByApartment_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDeliveryID provides a mock function with given fields: ctx, deliveryID
func (_m *DeliveryRepositoryPort) FindByDeliveryID(ctx context.Context, deliveryID string) (*entities.Delivery, error) {
	ret := _m.Called(ctx, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for FindByDeliveryID")
	}

	var r0 *entities.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Delivery, error)); ok {
		return rf(ctx, deliveryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Delivery); ok {
		r0 = rf(ctx, deliveryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deliveryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeliveryRepositoryPort_FindByDeliveryID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDeliveryID'
type DeliveryRepositoryPort_FindByDeliveryID_Call struct {
	*mock.Call
}

// FindByDeliveryID is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
func (_e *DeliveryRepositoryPort_Expecter) FindByDeliveryID(ctx interface{}, deliveryID interface{}) *DeliveryRepositoryPort_FindByDeliveryID_Call {
	return &DeliveryRepositoryPort_FindByDeliveryID_Call{Call: _e.mock.On("FindByDeliveryID", ctx, deliveryID)}
}

func (_c *DeliveryRepositoryPort_FindByDeliveryID_Call) Run(run func(ctx context.Context, deliveryID string)) *DeliveryRepositoryPort_FindByDeliveryID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeliveryRepositoryPort_FindByDeliveryID_Call) Return(_a0 *entities.Delivery, _a1 error) *DeliveryRepositoryPort_FindByDeliveryID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeliveryRepositoryPort_FindByDeliveryID_Call) RunAndReturn(run func(context.Context, string) (*entities.Delivery, error)) *DeliveryRepositoryPort_FindByDeliveryID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, delivery
func (_m *DeliveryRepositoryPort) Insert(ctx context.Context, delivery *entities.Delivery) error {
	ret := _m.Called(ctx, delivery)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Delivery) error); ok {
		r0 = rf(ctx, delivery)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeliveryRepositoryPort_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type DeliveryRepositoryPort_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - delivery *entities.Delivery
func (_e *DeliveryRepositoryPort_Expecter) Insert(ctx interface{}, delivery interface{}) *DeliveryRepositoryPort_Insert_Call {
	return &DeliveryRepositoryPort_Insert_Call{Call: _e.mock.On("Insert", ctx, delivery)}
}

func (_c *DeliveryRepositoryPort_Insert_Call) Run(run func(ctx context.Context, delivery *entities.Delivery)) *DeliveryRepositoryPort_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Delivery))
	})
	return _c
}

func (_c *DeliveryRepositoryPort_Insert_Call) Return(_a0 error) *DeliveryRepositoryPort_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeliveryRepositoryPort_Insert_Call) RunAndReturn(run func(context.Context, *entities.Delivery) error) *DeliveryRepositoryPort_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// MarkArrivalAsNotified provides a mock function with given fields: ctx, deliveryID
func (_m *DeliveryRepositoryPort) MarkArrivalAsNotified(ctx context.Context, deliveryID string) error {
	ret := _m.Called(ctx, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for MarkArrivalAsNotified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deliveryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeliveryRepositoryPort_MarkArrivalAsNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkArrivalAsNotified'
type DeliveryRepositoryPort_MarkArrivalAsNotified_Call struct {
	*mock.Call
}

// MarkArrivalAsNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
func (_e *DeliveryRepositoryPort_Expecter) MarkArrivalAsNotified(ctx interface{}, deliveryID interface{}) *DeliveryRepositoryPort_MarkArrivalAsNotified_Call {
	return &DeliveryRepositoryPort_MarkArrivalAsNotified_Call{Call: _e.mock.On("MarkArrivalAsNotified", ctx, deliveryID)}
}

func (_c *DeliveryRepositoryPort_MarkArrivalAsNotified_Call) Run(run func(ctx context.Context, deliveryID string)) *DeliveryRepositoryPort_MarkArrivalAsNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeliveryRepositoryPort_MarkArrivalAsNotified_Call) Return(_a0 error) *DeliveryRepositoryPort_MarkArrivalAsNotified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeliveryRepositoryPort_MarkArrivalAsNotified_Call) RunAndReturn(run func(context.Context, string) error) *DeliveryRepositoryPort_MarkArrivalAsNotified_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsDeleted provides a mock function with given fields: ctx, deliveryID
func (_m *DeliveryRepositoryPort) MarkAsDeleted(ctx context.Context, deliveryID string) error {
	ret := _m.Called(ctx, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deliveryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeliveryRepositoryPort_MarkAsDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsDeleted'
type DeliveryRepositoryPort_MarkAsDeleted_Call struct {
	*mock.Call
}

// MarkAsDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
func (_e *DeliveryRepositoryPort_Expecter) MarkAsDeleted(ctx interface{}, deliveryID interface{}) *DeliveryRepositoryPort_MarkAsDeleted_Call {
	return &DeliveryRepositoryPort_MarkAsDeleted_Call{Call: _e.mock.On("MarkAsDeleted", ctx, deliveryID)}
}

func (_c *DeliveryRepositoryPort_MarkAsDeleted_Call) Run(run func(ctx context.Context, deliveryID string)) *DeliveryRepositoryPort_MarkAsDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeliveryRepositoryPort_MarkAsDeleted_Call) Return(_a0 error) *DeliveryRepositoryPort_MarkAsDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeliveryRepositoryPort_MarkAsDeleted_Call) RunAndReturn(run func(context.Context, string) error) *DeliveryRepositoryPort_MarkAsDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPickupAsNotified provides a mock function with given fields: ctx, deliveryID
func (_m *DeliveryRepositoryPort) MarkPickupAsNotified(ctx context.Context, deliveryID string) error {
	ret := _m.Called(ctx, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPickupAsNotified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deliveryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeliveryRepositoryPort_MarkPickupAsNotified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPickupAsNotified'
type DeliveryRepositoryPort_MarkPickupAsNotified_Call struct {
	*mock.Call
}

// MarkPickupAsNotified is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
func (_e *DeliveryRepositoryPort_Expecter) MarkPickupAsNotified(ctx interface{}, deliveryID interface{}) *DeliveryRepositoryPort_MarkPickupAsNotified_Call {
	return &DeliveryRepositoryPort_MarkPickupAsNotified_Call{Call: _e.mock.On("MarkPickupAsNotified", ctx, deliveryID)}
}

func (_c *DeliveryRepositoryPort_MarkPickupAsNotified_Call) Run(run func(ctx context.Context, deliveryID string)) *DeliveryRepositoryPort_MarkPickupAsNotified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeliveryRepositoryPort_MarkPickupAsNotified_Call) Return(_a0 error) *DeliveryRepositoryPort_MarkPickupAsNotified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeliveryRepositoryPort_MarkPickupAsNotified_Call) RunAndReturn(run func(context.Context, string) error) *DeliveryRepositoryPort_MarkPickupAsNotified_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeliveryRepositoryPort creates a new instance of DeliveryRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveryRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveryRepositoryPort {
	mock := &DeliveryRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
