// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// ResidentRepository is an autogenerated mock type for the ResidentRepository type
type ResidentRepository struct {
	mock.Mock
}

type ResidentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ResidentRepository) EXPECT() *ResidentRepository_Expecter {
	return &ResidentRepository_Expecter{mock: &_m.Mock}
}

// DeleteByResidentID provides a mock function with given fields: ctx, residentID
func (_m *ResidentRepository) DeleteByResidentID(ctx context.Context, residentID string) error {
	ret := _m.Called(ctx, residentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByResidentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, residentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepository_DeleteByResidentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByResidentID'
type ResidentRepository_DeleteByResidentID_Call struct {
	*mock.Call
}

// DeleteByResidentID is a helper method to define mock.On call
//   - ctx context.Context
//   - residentID string
func (_e *ResidentRepository_Expecter) DeleteByResidentID(ctx interface{}, residentID interface{}) *ResidentRepository_DeleteByResidentID_Call {
	return &ResidentRepository_DeleteByResidentID_Call{Call: _e.mock.On("DeleteByResidentID", ctx, residentID)}
}

func (_c *ResidentRepository_DeleteByResidentID_Call) Run(run func(ctx context.Context, residentID string)) *ResidentRepository_DeleteByResidentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepository_DeleteByResidentID_Call) Return(_a0 error) *ResidentRepository_DeleteByResidentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepository_DeleteByResidentID_Call) RunAndReturn(run func(context.Context, string) error) *ResidentRepository_DeleteByResidentID_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureOtherResident provides a mock function with given fields: ctx, apartment
func (_m *ResidentRepository) EnsureOtherResident(ctx context.Context, apartment string) error {
	ret := _m.Called(ctx, apartment)

	if len(ret) == 0 {
		panic("no return value specified for EnsureOtherResident")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, apartment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepository_EnsureOtherResident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureOtherResident'
type ResidentRepository_EnsureOtherResident_Call struct {
	*mock.Call
}

// EnsureOtherResident is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
func (_e *ResidentRepository_Expecter) EnsureOtherResident(ctx interface{}, apartment interface{}) *ResidentRepository_EnsureOtherResident_Call {
	return &ResidentRepository_EnsureOtherResident_Call{Call: _e.mock.On("EnsureOtherResident", ctx, apartment)}
}

func (_c *ResidentRepository_EnsureOtherResident_Call) Run(run func(ctx context.Context, apartment string)) *ResidentRepository_EnsureOtherResident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepository_EnsureOtherResident_Call) Return(_a0 error) *ResidentRepository_EnsureOtherResident_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepository_EnsureOtherResident_Call) RunAndReturn(run func(context.Context, string) error) *ResidentRepository_EnsureOtherResident_Call {
	_c.Call.Return(run)
	return _c
}

// EnsurePrimaryResident provides a mock function with given fields: ctx, apartment
func (_m *ResidentRepository) EnsurePrimaryResident(ctx context.Context, apartment string) error {
	ret := _m.Called(ctx, apartment)

	if len(ret) == 0 {
		panic("no return value specified for EnsurePrimaryResident")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, apartment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepository_EnsurePrimaryResident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsurePrimaryResident'
type ResidentRepository_EnsurePrimaryResident_Call struct {
	*mock.Call
}

// EnsurePrimaryResident is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
func (_e *ResidentRepository_Expecter) EnsurePrimaryResident(ctx interface{}, apartment interface{}) *ResidentRepository_EnsurePrimaryResident_Call {
	return &ResidentRepository_EnsurePrimaryResident_Call{Call: _e.mock.On("EnsurePrimaryResident", ctx, apartment)}
}

func (_c *ResidentRepository_EnsurePrimaryResident_Call) Run(run func(ctx context.Context, apartment string)) *ResidentRepository_EnsurePrimaryResident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepository_EnsurePrimaryResident_Call) Return(_a0 error) *ResidentRepository_EnsurePrimaryResident_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepository_EnsurePrimaryResident_Call) RunAndReturn(run func(context.Context, string) error) *ResidentRepository_EnsurePrimaryResident_Call {
	_c.Call.Return(run)
	return _c
}

// FindByApartment provides a mock function with given fields: ctx, apartment
func (_m *ResidentRepository) FindByApartment(ctx context.Context, apartment string) ([]*entities.Resident, error) {
	ret := _m.Called(ctx, apartment)

	if len(ret) == 0 {
		panic("no return value specified for FindByApartment")
	}

	var r0 []*entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Resident, error)); ok {
		return rf(ctx, apartment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Resident); ok {
		r0 = rf(ctx, apartment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apartment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentRepository_FindByApartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByApartment'
type ResidentRepository_FindByApartment_Call struct {
	*mock.Call
}

// FindByApartment is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
func (_e *ResidentRepository_Expecter) FindByApartment(ctx interface{}, apartment interface{}) *ResidentRepository_FindByApartment_Call {
	return &ResidentRepository_FindByApartment_Call{Call: _e.mock.On("FindByApartment", ctx, apartment)}
}

func (_c *ResidentRepository_FindByApartment_Call) Run(run func(ctx context.Context, apartment string)) *ResidentRepository_FindByApartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepository_FindByApartment_Call) Return(_a0 []*entities.Resident, _a1 error) *ResidentRepository_FindByApartment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentRepository_FindByApartment_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Resident, error)) *ResidentRepository_FindByApartment_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPhone provides a mock function with given fields: ctx, phone
func (_m *ResidentRepository) FindByPhone(ctx context.Context, phone string) ([]*entities.Resident, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhone")
	}

	var r0 []*entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Resident, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Resident); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentRepository_FindByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPhone'
type ResidentRepository_FindByPhone_Call struct {
	*mock.Call
}

// FindByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *ResidentRepository_Expecter) FindByPhone(ctx interface{}, phone interface{}) *ResidentRepository_FindByPhone_Call {
	return &ResidentRepository_FindByPhone_Call{Call: _e.mock.On("FindByPhone", ctx, phone)}
}

func (_c *ResidentRepository_FindByPhone_Call) Run(run func(ctx context.Context, phone string)) *ResidentRepository_FindByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepository_FindByPhone_Call) Return(_a0 []*entities.Resident, _a1 error) *ResidentRepository_FindByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentRepository_FindByPhone_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Resident, error)) *ResidentRepository_FindByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResidentID provides a mock function with given fields: ctx, residentID
func (_m *ResidentRepository) FindByResidentID(ctx context.Context, residentID string) (*entities.Resident, error) {
	ret := _m.Called(ctx, residentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByResidentID")
	}

	var r0 *entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Resident, error)); ok {
		return rf(ctx, residentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Resident); ok {
		r0 = rf(ctx, residentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, residentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentRepository_FindByResidentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResidentID'
type ResidentRepository_FindByResidentID_Call struct {
	*mock.Call
}

// FindByResidentID is a helper method to define mock.On call
//   - ctx context.Context
//   - residentID string
func (_e *ResidentRepository_Expecter) FindByResidentID(ctx interface{}, residentID interface{}) *ResidentRepository_FindByResidentID_Call {
	return &ResidentRepository_FindByResidentID_Call{Call: _e.mock.On("FindByResidentID", ctx, residentID)}
}

func (_c *ResidentRepository_FindByResidentID_Call) Run(run func(ctx context.Context, residentID string)) *ResidentRepository_FindByResidentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepository_FindByResidentID_Call) Return(_a0 *entities.Resident, _a1 error) *ResidentRepository_FindByResidentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentRepository_FindByResidentID_Call) RunAndReturn(run func(context.Context, string) (*entities.Resident, error)) *ResidentRepository_FindByResidentID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, resident
func (_m *ResidentRepository) Insert(ctx context.Context, resident *entities.Resident) error {
	ret := _m.Called(ctx, resident)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Resident) error); ok {
		r0 = rf(ctx, resident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type ResidentRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - resident *entities.Resident
func (_e *ResidentRepository_Expecter) Insert(ctx interface{}, resident interface{}) *ResidentRepository_Insert_Call {
	return &ResidentRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, resident)}
}

func (_c *ResidentRepository_Insert_Call) Run(run func(ctx context.Context, resident *entities.Resident)) *ResidentRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Resident))
	})
	return _c
}

func (_c *ResidentRepository_Insert_Call) Return(_a0 error) *ResidentRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepository_Insert_Call) RunAndReturn(run func(context.Context, *entities.Resident) error) *ResidentRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, resident
func (_m *ResidentRepository) Update(ctx context.Context, resident *entities.Resident) error {
	ret := _m.Called(ctx, resident)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Resident) error); ok {
		r0 = rf(ctx, resident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ResidentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - resident *entities.Resident
func (_e *ResidentRepository_Expecter) Update(ctx interface{}, resident interface{}) *ResidentRepository_Update_Call {
	return &ResidentRepository_Update_Call{Call: _e.mock.On("Update", ctx, resident)}
}

func (_c *ResidentRepository_Update_Call) Run(run func(ctx context.Context, resident *entities.Resident)) *ResidentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Resident))
	})
	return _c
}

func (_c *ResidentRepository_Update_Call) Return(_a0 error) *ResidentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Resident) error) *ResidentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewResidentRepository creates a new instance of ResidentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResidentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResidentRepository {
	mock := &ResidentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
