// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// ResidentRepositoryPort is an autogenerated mock type for the ResidentRepositoryPort type
type ResidentRepositoryPort struct {
	mock.Mock
}

type ResidentRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *ResidentRepositoryPort) EXPECT() *ResidentRepositoryPort_Expecter {
	return &ResidentRepositoryPort_Expecter{mock: &_m.Mock}
}

// DeleteByResidentID provides a mock function with given fields: ctx, residentID
func (_m *ResidentRepositoryPort) DeleteByResidentID(ctx context.Context, residentID string) error {
	ret := _m.Called(ctx, residentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByResidentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, residentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepositoryPort_DeleteByResidentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByResidentID'
type ResidentRepositoryPort_DeleteByResidentID_Call struct {
	*mock.Call
}

// DeleteByResidentID is a helper method to define mock.On call
//   - ctx context.Context
//   - residentID string
func (_e *ResidentRepositoryPort_Expecter) DeleteByResidentID(ctx interface{}, residentID interface{}) *ResidentRepositoryPort_DeleteByResidentID_Call {
	return &ResidentRepositoryPort_DeleteByResidentID_Call{Call: _e.mock.On("DeleteByResidentID", ctx, residentID)}
}

func (_c *ResidentRepositoryPort_DeleteByResidentID_Call) Run(run func(ctx context.Context, residentID string)) *ResidentRepositoryPort_DeleteByResidentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepositoryPort_DeleteByResidentID_Call) Return(_a0 error) *ResidentRepositoryPort_DeleteByResidentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepositoryPort_DeleteByResidentID_Call) RunAndReturn(run func(context.Context, string) error) *ResidentRepositoryPort_DeleteByResidentID_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureOtherResident provides a mock function with given fields: ctx, apartment
func (_m *ResidentRepositoryPort) EnsureOtherResident(ctx context.Context, apartment string) error {
	ret := _m.Called(ctx, apartment)

	if len(ret) == 0 {
		panic("no return value specified for EnsureOtherResident")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, apartment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepositoryPort_EnsureOtherResident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureOtherResident'
type ResidentRepositoryPort_EnsureOtherResident_Call struct {
	*mock.Call
}

// EnsureOtherResident is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
func (_e *ResidentRepositoryPort_Expecter) EnsureOtherResident(ctx interface{}, apartment interface{}) *ResidentRepositoryPort_EnsureOtherResident_Call {
	return &ResidentRepositoryPort_EnsureOtherResident_Call{Call: _e.mock.On("EnsureOtherResident", ctx, apartment)}
}

func (_c *ResidentRepositoryPort_EnsureOtherResident_Call) Run(run func(ctx context.Context, apartment string)) *ResidentRepositoryPort_EnsureOtherResident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepositoryPort_EnsureOtherResident_Call) Return(_a0 error) *ResidentRepositoryPort_EnsureOtherResident_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepositoryPort_EnsureOtherResident_Call) RunAndReturn(run func(context.Context, string) error) *ResidentRepositoryPort_EnsureOtherResident_Call {
	_c.Call.Return(run)
	return _c
}

// EnsurePrimaryResident provides a mock function with given fields: ctx, apartment
func (_m *ResidentRepositoryPort) EnsurePrimaryResident(ctx context.Context, apartment string) error {
	ret := _m.Called(ctx, apartment)

	if len(ret) == 0 {
		panic("no return value specified for EnsurePrimaryResident")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, apartment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepositoryPort_EnsurePrimaryResident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsurePrimaryResident'
type ResidentRepositoryPort_EnsurePrimaryResident_Call struct {
	*mock.Call
}

// EnsurePrimaryResident is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
func (_e *ResidentRepositoryPort_Expecter) EnsurePrimaryResident(ctx interface{}, apartment interface{}) *ResidentRepositoryPort_EnsurePrimaryResident_Call {
	return &ResidentRepositoryPort_EnsurePrimaryResident_Call{Call: _e.mock.On("EnsurePrimaryResident", ctx, apartment)}
}

func (_c *ResidentRepositoryPort_EnsurePrimaryResident_Call) Run(run func(ctx context.Context, apartment string)) *ResidentRepositoryPort_EnsurePrimaryResident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepositoryPort_EnsurePrimaryResident_Call) Return(_a0 error) *ResidentRepositoryPort_EnsurePrimaryResident_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepositoryPort_EnsurePrimaryResident_Call) RunAndReturn(run func(context.Context, string) error) *ResidentRepositoryPort_EnsurePrimaryResident_Call {
	_c.Call.Return(run)
	return _c
}

// FindByApartment provides a mock function with given fields: ctx, apartment
func (_m *ResidentRepositoryPort) FindByApartment(ctx context.Context, apartment string) ([]*entities.Resident, error) {
	ret := _m.Called(ctx, apartment)

	if len(ret) == 0 {
		panic("no return value specified for FindByApartment")
	}

	var r0 []*entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Resident, error)); ok {
		return rf(ctx, apartment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Resident); ok {
		r0 = rf(ctx, apartment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apartment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentRepositoryPort_FindByApartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByApartment'
type ResidentRepositoryPort_FindByApartment_Call struct {
	*mock.Call
}

// FindByApartment is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
func (_e *ResidentRepositoryPort_Expecter) FindByApartment(ctx interface{}, apartment interface{}) *ResidentRepositoryPort_FindByApartment_Call {
	return &ResidentRepositoryPort_FindByApartment_Call{Call: _e.mock.On("FindByApartment", ctx, apartment)}
}

func (_c *ResidentRepositoryPort_FindByApartment_Call) Run(run func(ctx context.Context, apartment string)) *ResidentRepositoryPort_FindByApartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepositoryPort_FindByApartment_Call) Return(_a0 []*entities.Resident, _a1 error) *ResidentRepositoryPort_FindByApartment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentRepositoryPort_FindByApartment_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Resident, error)) *ResidentRepositoryPort_FindByApartment_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPhone provides a mock function with given fields: ctx, phone
func (_m *ResidentRepositoryPort) FindByPhone(ctx context.Context, phone string) ([]*entities.Resident, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhone")
	}

	var r0 []*entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Resident, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Resident); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentRepositoryPort_FindByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPhone'
type ResidentRepositoryPort_FindByPhone_Call struct {
	*mock.Call
}

// FindByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *ResidentRepositoryPort_Expecter) FindByPhone(ctx interface{}, phone interface{}) *ResidentRepositoryPort_FindByPhone_Call {
	return &ResidentRepositoryPort_FindByPhone_Call{Call: _e.mock.On("FindByPhone", ctx, phone)}
}

func (_c *ResidentRepositoryPort_FindByPhone_Call) Run(run func(ctx context.Context, phone string)) *ResidentRepositoryPort_FindByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepositoryPort_FindByPhone_Call) Return(_a0 []*entities.Resident, _a1 error) *ResidentRepositoryPort_FindByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentRepositoryPort_FindByPhone_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Resident, error)) *ResidentRepositoryPort_FindByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResidentID provides a mock function with given fields: ctx, residentID
func (_m *ResidentRepositoryPort) FindByResidentID(ctx context.Context, residentID string) (*entities.Resident, error) {
	ret := _m.Called(ctx, residentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByResidentID")
	}

	var r0 *entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Resident, error)); ok {
		return rf(ctx, residentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Resident); ok {
		r0 = rf(ctx, residentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, residentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentRepositoryPort_FindByResidentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResidentID'
type ResidentRepositoryPort_FindByResidentID_Call struct {
	*mock.Call
}

// FindByResidentID is a helper method to define mock.On call
//   - ctx context.Context
//   - residentID string
func (_e *ResidentRepositoryPort_Expecter) FindByResidentID(ctx interface{}, residentID interface{}) *ResidentRepositoryPort_FindByResidentID_Call {
	return &ResidentRepositoryPort_FindByResidentID_Call{Call: _e.mock.On("FindByResidentID", ctx, residentID)}
}

func (_c *ResidentRepositoryPort_FindByResidentID_Call) Run(run func(ctx context.Context, residentID string)) *ResidentRepositoryPort_FindByResidentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentRepositoryPort_FindByResidentID_Call) Return(_a0 *entities.Resident, _a1 error) *ResidentRepositoryPort_FindByResidentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentRepositoryPort_FindByResidentID_Call) RunAndReturn(run func(context.Context, string) (*entities.Resident, error)) *ResidentRepositoryPort_FindByResidentID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, resident
func (_m *ResidentRepositoryPort) Insert(ctx context.Context, resident *entities.Resident) error {
	ret := _m.Called(ctx, resident)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Resident) error); ok {
		r0 = rf(ctx, resident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepositoryPort_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type ResidentRepositoryPort_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - resident *entities.Resident
func (_e *ResidentRepositoryPort_Expecter) Insert(ctx interface{}, resident interface{}) *ResidentRepositoryPort_Insert_Call {
	return &ResidentRepositoryPort_Insert_Call{Call: _e.mock.On("Insert", ctx, resident)}
}

func (_c *ResidentRepositoryPort_Insert_Call) Run(run func(ctx context.Context, resident *entities.Resident)) *ResidentRepositoryPort_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Resident))
	})
	return _c
}

func (_c *ResidentRepositoryPort_Insert_Call) Return(_a0 error) *ResidentRepositoryPort_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepositoryPort_Insert_Call) RunAndReturn(run func(context.Context, *entities.Resident) error) *ResidentRepositoryPort_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, resident
func (_m *ResidentRepositoryPort) Update(ctx context.Context, resident *entities.Resident) error {
	ret := _m.Called(ctx, resident)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Resident) error); ok {
		r0 = rf(ctx, resident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResidentRepositoryPort_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ResidentRepositoryPort_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - resident *entities.Resident
func (_e *ResidentRepositoryPort_Expecter) Update(ctx interface{}, resident interface{}) *ResidentRepositoryPort_Update_Call {
	return &ResidentRepositoryPort_Update_Call{Call: _e.mock.On("Update", ctx, resident)}
}

func (_c *ResidentRepositoryPort_Update_Call) Run(run func(ctx context.Context, resident *entities.Resident)) *ResidentRepositoryPort_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Resident))
	})
	return _c
}

func (_c *ResidentRepositoryPort_Update_Call) Return(_a0 error) *ResidentRepositoryPort_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResidentRepositoryPort_Update_Call) RunAndReturn(run func(context.Context, *entities.Resident) error) *ResidentRepositoryPort_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewResidentRepositoryPort creates a new instance of ResidentRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResidentRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResidentRepositoryPort {
	mock := &ResidentRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
