// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NotificationScheduler is an autogenerated mock type for the NotificationScheduler type
type NotificationScheduler struct {
	mock.Mock
}

type NotificationScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationScheduler) EXPECT() *NotificationScheduler_Expecter {
	return &NotificationScheduler_Expecter{mock: &_m.Mock}
}

// Schedule provides a mock function with given fields: ctx, deliveryID, notificationType
func (_m *NotificationScheduler) Schedule(ctx context.Context, deliveryID string, notificationType entities.NotificationType) error {
	ret := _m.Called(ctx, deliveryID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.NotificationType) error); ok {
		r0 = rf(ctx, deliveryID, notificationType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationScheduler_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type NotificationScheduler_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
//   - notificationType entities.NotificationType
func (_e *NotificationScheduler_Expecter) Schedule(ctx interface{}, deliveryID interface{}, notificationType interface{}) *NotificationScheduler_Schedule_Call {
	return &NotificationScheduler_Schedule_Call{Call: _e.mock.On("Schedule", ctx, deliveryID, notificationType)}
}

func (_c *NotificationScheduler_Schedule_Call) Run(run func(ctx context.Context, deliveryID string, notificationType entities.NotificationType)) *NotificationScheduler_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(entities.NotificationType))
	})
	return _c
}

func (_c *NotificationScheduler_Schedule_Call) Return(_a0 error) *NotificationScheduler_Schedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationScheduler_Schedule_Call) RunAndReturn(run func(context.Context, string, entities.NotificationType) error) *NotificationScheduler_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationScheduler creates a new instance of NotificationScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationScheduler {
	mock := &NotificationScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
