// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// TokenVerifier is an autogenerated mock type for the TokenVerifier type
type TokenVerifier struct {
	mock.Mock
}

type TokenVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenVerifier) EXPECT() *TokenVerifier_Expecter {
	return &TokenVerifier_Expecter{mock: &_m.Mock}
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *TokenVerifier) VerifyToken(ctx context.Context, token string) (*entities.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenVerifier_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type TokenVerifier_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenVerifier_Expecter) VerifyToken(ctx interface{}, token interface{}) *TokenVerifier_VerifyToken_Call {
	return &TokenVerifier_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *TokenVerifier_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *TokenVerifier_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenVerifier_VerifyToken_Call) Return(_a0 *entities.User, _a1 error) *TokenVerifier_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenVerifier_VerifyToken_Call) RunAndReturn(run func(context.Context, string) (*entities.User, error)) *TokenVerifier_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenVerifier creates a new instance of TokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenVerifier {
	mock := &TokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
