// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// UserRegistry is an autogenerated mock type for the UserRegistry type
type UserRegistry struct {
	mock.Mock
}

type UserRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRegistry) EXPECT() *UserRegistry_Expecter {
	return &UserRegistry_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user, password
func (_m *UserRegistry) CreateUser(ctx context.Context, user *entities.User, password string) (*entities.User, error) {
	ret := _m.Called(ctx, user, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User, string) (*entities.User, error)); ok {
		return rf(ctx, user, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User, string) *entities.User); ok {
		r0 = rf(ctx, user, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.User, string) error); ok {
		r1 = rf(ctx, user, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRegistry_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRegistry_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
//   - password string
func (_e *UserRegistry_Expecter) CreateUser(ctx interface{}, user interface{}, password interface{}) *UserRegistry_CreateUser_Call {
	return &UserRegistry_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user, password)}
}

func (_c *UserRegistry_CreateUser_Call) Run(run func(ctx context.Context, user *entities.User, password string)) *UserRegistry_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User), args[2].(string))
	})
	return _c
}

func (_c *UserRegistry_CreateUser_Call) Return(_a0 *entities.User, _a1 error) *UserRegistry_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRegistry_CreateUser_Call) RunAndReturn(run func(context.Context, *entities.User, string) (*entities.User, error)) *UserRegistry_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRegistry creates a new instance of UserRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRegistry {
	mock := &UserRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
