// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Moreira-Henrique-Pedro/entregador/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CreateResident is an autogenerated mock type for the CreateResident type
type CreateResident struct {
	mock.Mock
}

type CreateResident_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateResident) EXPECT() *CreateResident_Expecter {
	return &CreateResident_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, resident
func (_m *CreateResident) Execute(ctx context.Context, resident *domain.Resident) (*domain.Resident, error) {
	ret := _m.Called(ctx, resident)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Resident) (*domain.Resident, error)); ok {
		return rf(ctx, resident)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Resident) *domain.Resident); ok {
		r0 = rf(ctx, resident)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Resident) error); ok {
		r1 = rf(ctx, resident)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateResident_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CreateResident_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - resident *domain.Resident
func (_e *CreateResident_Expecter) Execute(ctx interface{}, resident interface{}) *CreateResident_Execute_Call {
	return &CreateResident_Execute_Call{Call: _e.mock.On("Execute", ctx, resident)}
}

func (_c *CreateResident_Execute_Call) Run(run func(ctx context.Context, resident *domain.Resident)) *CreateResident_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Resident))
	})
	return _c
}

func (_c *CreateResident_Execute_Call) Return(_a0 *domain.Resident, _a1 error) *CreateResident_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreateResident_Execute_Call) RunAndReturn(run func(context.Context, *domain.Resident) (*domain.Resident, error)) *CreateResident_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateResident creates a new instance of CreateResident. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateResident(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateResident {
	mock := &CreateResident{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
