// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteResident is an autogenerated mock type for the DeleteResident type
type DeleteResident struct {
	mock.Mock
}

type DeleteResident_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteResident) EXPECT() *DeleteResident_Expecter {
	return &DeleteResident_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, residentID
func (_m *DeleteResident) Execute(ctx context.Context, residentID string) error {
	ret := _m.Called(ctx, residentID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, residentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteResident_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteResident_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - residentID string
func (_e *DeleteResident_Expecter) Execute(ctx interface{}, residentID interface{}) *DeleteResident_Execute_Call {
	return &DeleteResident_Execute_Call{Call: _e.mock.On("Execute", ctx, residentID)}
}

func (_c *DeleteResident_Execute_Call) Run(run func(ctx context.Context, residentID string)) *DeleteResident_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeleteResident_Execute_Call) Return(_a0 error) *DeleteResident_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteResident_Execute_Call) RunAndReturn(run func(context.Context, string) error) *DeleteResident_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteResident creates a new instance of DeleteResident. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteResident(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteResident {
	mock := &DeleteResident{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
