// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Moreira-Henrique-Pedro/entregador/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ListDeliveries is an autogenerated mock type for the ListDeliveries type
type ListDeliveries struct {
	mock.Mock
}

type ListDeliveries_Expecter struct {
	mock *mock.Mock
}

func (_m *ListDeliveries) EXPECT() *ListDeliveries_Expecter {
	return &ListDeliveries_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, apartment, status
func (_m *ListDeliveries) Execute(ctx context.Context, apartment string, status *domain.DeliveryStatus) ([]*domain.Delivery, error) {
	ret := _m.Called(ctx, apartment, status)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*domain.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.DeliveryStatus) ([]*domain.Delivery, error)); ok {
		return rf(ctx, apartment, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.DeliveryStatus) []*domain.Delivery); ok {
		r0 = rf(ctx, apartment, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.DeliveryStatus) error); ok {
		r1 = rf(ctx, apartment, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDeliveries_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListDeliveries_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
//   - status *domain.DeliveryStatus
func (_e *ListDeliveries_Expecter) Execute(ctx interface{}, apartment interface{}, status interface{}) *ListDeliveries_Execute_Call {
	return &ListDeliveries_Execute_Call{Call: _e.mock.On("Execute", ctx, apartment, status)}
}

func (_c *ListDeliveries_Execute_Call) Run(run func(ctx context.Context, apartment string, status *domain.DeliveryStatus)) *ListDeliveries_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*domain.DeliveryStatus))
	})
	return _c
}

func (_c *ListDeliveries_Execute_Call) Return(_a0 []*domain.Delivery, _a1 error) *ListDeliveries_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListDeliveries_Execute_Call) RunAndReturn(run func(context.Context, string, *domain.DeliveryStatus) ([]*domain.Delivery, error)) *ListDeliveries_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListDeliveries creates a new instance of ListDeliveries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListDeliveries(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListDeliveries {
	mock := &ListDeliveries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
