// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Moreira-Henrique-Pedro/entregador/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotifyDelivery is an autogenerated mock type for the NotifyDelivery type
type NotifyDelivery struct {
	mock.Mock
}

type NotifyDelivery_Expecter struct {
	mock *mock.Mock
}

func (_m *NotifyDelivery) EXPECT() *NotifyDelivery_Expecter {
	return &NotifyDelivery_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, deliveryID, notificationType
func (_m *NotifyDelivery) Execute(ctx context.Context, deliveryID string, notificationType domain.NotificationType) error {
	ret := _m.Called(ctx, deliveryID, notificationType)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.NotificationType) error); ok {
		r0 = rf(ctx, deliveryID, notificationType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyDelivery_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type NotifyDelivery_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
//   - notificationType domain.NotificationType
func (_e *NotifyDelivery_Expecter) Execute(ctx interface{}, deliveryID interface{}, notificationType interface{}) *NotifyDelivery_Execute_Call {
	return &NotifyDelivery_Execute_Call{Call: _e.mock.On("Execute", ctx, deliveryID, notificationType)}
}

func (_c *NotifyDelivery_Execute_Call) Run(run func(ctx context.Context, deliveryID string, notificationType domain.NotificationType)) *NotifyDelivery_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.NotificationType))
	})
	return _c
}

func (_c *NotifyDelivery_Execute_Call) Return(_a0 error) *NotifyDelivery_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifyDelivery_Execute_Call) RunAndReturn(run func(context.Context, string, domain.NotificationType) error) *NotifyDelivery_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifyDelivery creates a new instance of NotifyDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifyDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotifyDelivery {
	mock := &NotifyDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
