// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pubsub "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/interfaces/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher[T any] struct {
	mock.Mock
}

type MessagePublisher_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MessagePublisher[T]) EXPECT() *MessagePublisher_Expecter[T] {
	return &MessagePublisher_Expecter[T]{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MessagePublisher[T]) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessagePublisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MessagePublisher_Close_Call[T any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MessagePublisher_Expecter[T]) Close(ctx interface{}) *MessagePublisher_Close_Call[T] {
	return &MessagePublisher_Close_Call[T]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MessagePublisher_Close_Call[T]) Run(run func(ctx context.Context)) *MessagePublisher_Close_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MessagePublisher_Close_Call[T]) Return(_a0 error) *MessagePublisher_Close_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessagePublisher_Close_Call[T]) RunAndReturn(run func(context.Context) error) *MessagePublisher_Close_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, topic, messages
func (_m *MessagePublisher[T]) Publish(ctx context.Context, topic string, messages ...*pubsub.Message[T]) error {
	_va := make([]interface{}, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, topic)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...*pubsub.Message[T]) error); ok {
		r0 = rf(ctx, topic, messages...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessagePublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MessagePublisher_Publish_Call[T any] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - messages ...*pubsub.Message[T]
func (_e *MessagePublisher_Expecter[T]) Publish(ctx interface{}, topic interface{}, messages ...interface{}) *MessagePublisher_Publish_Call[T] {
	return &MessagePublisher_Publish_Call[T]{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, topic}, messages...)...)}
}

func (_c *MessagePublisher_Publish_Call[T]) Run(run func(ctx context.Context, topic string, messages ...*pubsub.Message[T])) *MessagePublisher_Publish_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*pubsub.Message[T], len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*pubsub.Message[T])
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MessagePublisher_Publish_Call[T]) Return(_a0 error) *MessagePublisher_Publish_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessagePublisher_Publish_Call[T]) RunAndReturn(run func(context.Context, string, ...*pubsub.Message[T]) error) *MessagePublisher_Publish_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMessagePublisher creates a new instance of MessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagePublisher[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagePublisher[T] {
	mock := &MessagePublisher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
