// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	notifier "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/interfaces/notifier"
	mock "github.com/stretchr/testify/mock"
)

// NotifierPort is an autogenerated mock type for the NotifierPort type
type NotifierPort struct {
	mock.Mock
}

type NotifierPort_Expecter struct {
	mock *mock.Mock
}

func (_m *NotifierPort) EXPECT() *NotifierPort_Expecter {
	return &NotifierPort_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, notification
func (_m *NotifierPort) Send(ctx context.Context, notification notifier.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, notifier.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifierPort_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type NotifierPort_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - notification notifier.Notification
func (_e *NotifierPort_Expecter) Send(ctx interface{}, notification interface{}) *NotifierPort_Send_Call {
	return &NotifierPort_Send_Call{Call: _e.mock.On("Send", ctx, notification)}
}

func (_c *NotifierPort_Send_Call) Run(run func(ctx context.Context, notification notifier.Notification)) *NotifierPort_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(notifier.Notification))
	})
	return _c
}

func (_c *NotifierPort_Send_Call) Return(_a0 error) *NotifierPort_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifierPort_Send_Call) RunAndReturn(run func(context.Context, notifier.Notification) error) *NotifierPort_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifierPort creates a new instance of NotifierPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifierPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotifierPort {
	mock := &NotifierPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
