// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeleteDelivery is an autogenerated mock type for the DeleteDelivery type
type DeleteDelivery struct {
	mock.Mock
}

type DeleteDelivery_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteDelivery) EXPECT() *DeleteDelivery_Expecter {
	return &DeleteDelivery_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, deliveryID
func (_m *DeleteDelivery) Execute(ctx context.Context, deliveryID string) error {
	ret := _m.Called(ctx, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deliveryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDelivery_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteDelivery_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
func (_e *DeleteDelivery_Expecter) Execute(ctx interface{}, deliveryID interface{}) *DeleteDelivery_Execute_Call {
	return &DeleteDelivery_Execute_Call{Call: _e.mock.On("Execute", ctx, deliveryID)}
}

func (_c *DeleteDelivery_Execute_Call) Run(run func(ctx context.Context, deliveryID string)) *DeleteDelivery_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeleteDelivery_Execute_Call) Return(_a0 error) *DeleteDelivery_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteDelivery_Execute_Call) RunAndReturn(run func(context.Context, string) error) *DeleteDelivery_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteDelivery creates a new instance of DeleteDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteDelivery {
	mock := &DeleteDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
