// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ListApartments is an autogenerated mock type for the ListApartments type
type ListApartments struct {
	mock.Mock
}

type ListApartments_Expecter struct {
	mock *mock.Mock
}

func (_m *ListApartments) EXPECT() *ListApartments_Expecter {
	return &ListApartments_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ListApartments) Execute(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListApartments_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListApartments_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ListApartments_Expecter) Execute(ctx interface{}) *ListApartments_Execute_Call {
	return &ListApartments_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ListApartments_Execute_Call) Run(run func(ctx context.Context)) *ListApartments_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ListApartments_Execute_Call) Return(_a0 []string, _a1 error) *ListApartments_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListApartments_Execute_Call) RunAndReturn(run func(context.Context) ([]string, error)) *ListApartments_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListApartments creates a new instance of ListApartments. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListApartments(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListApartments {
	mock := &ListApartments{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
