// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// ListResidents is an autogenerated mock type for the ListResidents type
type ListResidents struct {
	mock.Mock
}

type ListResidents_Expecter struct {
	mock *mock.Mock
}

func (_m *ListResidents) EXPECT() *ListResidents_Expecter {
	return &ListResidents_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, value
func (_m *ListResidents) Execute(ctx context.Context, value string) ([]*entities.Resident, error) {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Resident, error)); ok {
		return rf(ctx, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Resident); ok {
		r0 = rf(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListResidents_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ListResidents_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - value string
func (_e *ListResidents_Expecter) Execute(ctx interface{}, value interface{}) *ListResidents_Execute_Call {
	return &ListResidents_Execute_Call{Call: _e.mock.On("Execute", ctx, value)}
}

func (_c *ListResidents_Execute_Call) Run(run func(ctx context.Context, value string)) *ListResidents_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ListResidents_Execute_Call) Return(_a0 []*entities.Resident, _a1 error) *ListResidents_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ListResidents_Execute_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Resident, error)) *ListResidents_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListResidents creates a new instance of ListResidents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListResidents(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListResidents {
	mock := &ListResidents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
