// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// RegisterDelivery is an autogenerated mock type for the RegisterDelivery type
type RegisterDelivery struct {
	mock.Mock
}

type RegisterDelivery_Expecter struct {
	mock *mock.Mock
}

func (_m *RegisterDelivery) EXPECT() *RegisterDelivery_Expecter {
	return &RegisterDelivery_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, delivery
func (_m *RegisterDelivery) Execute(ctx context.Context, delivery *entities.Delivery) (*entities.Delivery, error) {
	ret := _m.Called(ctx, delivery)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Delivery) (*entities.Delivery, error)); ok {
		return rf(ctx, delivery)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Delivery) *entities.Delivery); ok {
		r0 = rf(ctx, delivery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Delivery) error); ok {
		r1 = rf(ctx, delivery)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterDelivery_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RegisterDelivery_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - delivery *entities.Delivery
func (_e *RegisterDelivery_Expecter) Execute(ctx interface{}, delivery interface{}) *RegisterDelivery_Execute_Call {
	return &RegisterDelivery_Execute_Call{Call: _e.mock.On("Execute", ctx, delivery)}
}

func (_c *RegisterDelivery_Execute_Call) Run(run func(ctx context.Context, delivery *entities.Delivery)) *RegisterDelivery_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Delivery))
	})
	return _c
}

func (_c *RegisterDelivery_Execute_Call) Return(_a0 *entities.Delivery, _a1 error) *RegisterDelivery_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegisterDelivery_Execute_Call) RunAndReturn(run func(context.Context, *entities.Delivery) (*entities.Delivery, error)) *RegisterDelivery_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegisterDelivery creates a new instance of RegisterDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterDelivery {
	mock := &RegisterDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
