// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// UpdateResident is an autogenerated mock type for the UpdateResident type
type UpdateResident struct {
	mock.Mock
}

type UpdateResident_Expecter struct {
	mock *mock.Mock
}

func (_m *UpdateResident) EXPECT() *UpdateResident_Expecter {
	return &UpdateResident_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, resident
func (_m *UpdateResident) Execute(ctx context.Context, resident *entities.Resident) (*entities.Resident, error) {
	ret := _m.Called(ctx, resident)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Resident) (*entities.Resident, error)); ok {
		return rf(ctx, resident)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Resident) *entities.Resident); ok {
		r0 = rf(ctx, resident)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.Resident) error); ok {
		r1 = rf(ctx, resident)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateResident_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UpdateResident_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - resident *entities.Resident
func (_e *UpdateResident_Expecter) Execute(ctx interface{}, resident interface{}) *UpdateResident_Execute_Call {
	return &UpdateResident_Execute_Call{Call: _e.mock.On("Execute", ctx, resident)}
}

func (_c *UpdateResident_Execute_Call) Run(run func(ctx context.Context, resident *entities.Resident)) *UpdateResident_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Resident))
	})
	return _c
}

func (_c *UpdateResident_Execute_Call) Return(_a0 *entities.Resident, _a1 error) *UpdateResident_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpdateResident_Execute_Call) RunAndReturn(run func(context.Context, *entities.Resident) (*entities.Resident, error)) *UpdateResident_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpdateResident creates a new instance of UpdateResident. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateResident(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateResident {
	mock := &UpdateResident{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
