// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// DeliveriesReaderPort is an autogenerated mock type for the DeliveriesReaderPort type
type DeliveriesReaderPort struct {
	mock.Mock
}

type DeliveriesReaderPort_Expecter struct {
	mock *mock.Mock
}

func (_m *DeliveriesReaderPort) EXPECT() *DeliveriesReaderPort_Expecter {
	return &DeliveriesReaderPort_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, apartment, status
func (_m *DeliveriesReaderPort) Handle(ctx context.Context, apartment string, status *entities.DeliveryStatus) ([]*entities.Delivery, error) {
	ret := _m.Called(ctx, apartment, status)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 []*entities.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.DeliveryStatus) ([]*entities.Delivery, error)); ok {
		return rf(ctx, apartment, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.DeliveryStatus) []*entities.Delivery); ok {
		r0 = rf(ctx, apartment, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *entities.DeliveryStatus) error); ok {
		r1 = rf(ctx, apartment, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeliveriesReaderPort_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type DeliveriesReaderPort_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - apartment string
//   - status *entities.DeliveryStatus
func (_e *DeliveriesReaderPort_Expecter) Handle(ctx interface{}, apartment interface{}, status interface{}) *DeliveriesReaderPort_Handle_Call {
	return &DeliveriesReaderPort_Handle_Call{Call: _e.mock.On("Handle", ctx, apartment, status)}
}

func (_c *DeliveriesReaderPort_Handle_Call) Run(run func(ctx context.Context, apartment string, status *entities.DeliveryStatus)) *DeliveriesReaderPort_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*entities.DeliveryStatus))
	})
	return _c
}

func (_c *DeliveriesReaderPort_Handle_Call) Return(_a0 []*entities.Delivery, _a1 error) *DeliveriesReaderPort_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeliveriesReaderPort_Handle_Call) RunAndReturn(run func(context.Context, string, *entities.DeliveryStatus) ([]*entities.Delivery, error)) *DeliveriesReaderPort_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeliveriesReaderPort creates a new instance of DeliveriesReaderPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveriesReaderPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveriesReaderPort {
	mock := &DeliveriesReaderPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
