// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Moreira-Henrique-Pedro/entregador/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// ResidentsReaderPort is an autogenerated mock type for the ResidentsReaderPort type
type ResidentsReaderPort struct {
	mock.Mock
}

type ResidentsReaderPort_Expecter struct {
	mock *mock.Mock
}

func (_m *ResidentsReaderPort) EXPECT() *ResidentsReaderPort_Expecter {
	return &ResidentsReaderPort_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, value
func (_m *ResidentsReaderPort) Handle(ctx context.Context, value string) ([]*entities.Resident, error) {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 []*entities.Resident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.Resident, error)); ok {
		return rf(ctx, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.Resident); ok {
		r0 = rf(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResidentsReaderPort_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type ResidentsReaderPort_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - value string
func (_e *ResidentsReaderPort_Expecter) Handle(ctx interface{}, value interface{}) *ResidentsReaderPort_Handle_Call {
	return &ResidentsReaderPort_Handle_Call{Call: _e.mock.On("Handle", ctx, value)}
}

func (_c *ResidentsReaderPort_Handle_Call) Run(run func(ctx context.Context, value string)) *ResidentsReaderPort_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ResidentsReaderPort_Handle_Call) Return(_a0 []*entities.Resident, _a1 error) *ResidentsReaderPort_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResidentsReaderPort_Handle_Call) RunAndReturn(run func(context.Context, string) ([]*entities.Resident, error)) *ResidentsReaderPort_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewResidentsReaderPort creates a new instance of ResidentsReaderPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResidentsReaderPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResidentsReaderPort {
	mock := &ResidentsReaderPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
