// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	mongo "go.mongodb.org/mongo-driver/mongo"

	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MongoClientCollectionPort is an autogenerated mock type for the MongoClientCollectionPort type
type MongoClientCollectionPort struct {
	mock.Mock
}

type MongoClientCollectionPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MongoClientCollectionPort) EXPECT() *MongoClientCollectionPort_Expecter {
	return &MongoClientCollectionPort_Expecter{mock: &_m.Mock}
}

// DeleteOne provides a mock function with given fields: ctx, filter, opts
func (_m *MongoClientCollectionPort) DeleteOne(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.DeleteOptions) (*mongo.DeleteResult, error)); ok {
		return rf(ctx, filter, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.DeleteOptions) *mongo.DeleteResult); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.DeleteOptions) error); ok {
		r1 = rf(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoClientCollectionPort_DeleteOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOne'
type MongoClientCollectionPort_DeleteOne_Call struct {
	*mock.Call
}

// DeleteOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.DeleteOptions
func (_e *MongoClientCollectionPort_Expecter) DeleteOne(ctx interface{}, filter interface{}, opts ...interface{}) *MongoClientCollectionPort_DeleteOne_Call {
	return &MongoClientCollectionPort_DeleteOne_Call{Call: _e.mock.On("DeleteOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MongoClientCollectionPort_DeleteOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions)) *MongoClientCollectionPort_DeleteOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.DeleteOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.DeleteOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoClientCollectionPort_DeleteOne_Call) Return(_a0 *mongo.DeleteResult, _a1 error) *MongoClientCollectionPort_DeleteOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoClientCollectionPort_DeleteOne_Call) RunAndReturn(run func(context.Context, interface{}, ...*options.DeleteOptions) (*mongo.DeleteResult, error)) *MongoClientCollectionPort_DeleteOne_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureIndexes provides a mock function with given fields: ctx, indexes
func (_m *MongoClientCollectionPort) EnsureIndexes(ctx context.Context, indexes []mongo.IndexModel) error {
	ret := _m.Called(ctx, indexes)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIndexes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []mongo.IndexModel) error); ok {
		r0 = rf(ctx, indexes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MongoClientCollectionPort_EnsureIndexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureIndexes'
type MongoClientCollectionPort_EnsureIndexes_Call struct {
	*mock.Call
}

// EnsureIndexes is a helper method to define mock.On call
//   - ctx context.Context
//   - indexes []mongo.IndexModel
func (_e *MongoClientCollectionPort_Expecter) EnsureIndexes(ctx interface{}, indexes interface{}) *MongoClientCollectionPort_EnsureIndexes_Call {
	return &MongoClientCollectionPort_EnsureIndexes_Call{Call: _e.mock.On("EnsureIndexes", ctx, indexes)}
}

func (_c *MongoClientCollectionPort_EnsureIndexes_Call) Run(run func(ctx context.Context, indexes []mongo.IndexModel)) *MongoClientCollectionPort_EnsureIndexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]mongo.IndexModel))
	})
	return _c
}

func (_c *MongoClientCollectionPort_EnsureIndexes_Call) Return(_a0 error) *MongoClientCollectionPort_EnsureIndexes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoClientCollectionPort_EnsureIndexes_Call) RunAndReturn(run func(context.Context, []mongo.IndexModel) error) *MongoClientCollectionPort_EnsureIndexes_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter, opts
func (_m *MongoClientCollectionPort) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (*mongo.Cursor, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *mongo.Cursor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) (*mongo.Cursor, error)); ok {
		return rf(ctx, filter, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) *mongo.Cursor); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Cursor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.FindOptions) error); ok {
		r1 = rf(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoClientCollectionPort_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MongoClientCollectionPort_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOptions
func (_e *MongoClientCollectionPort_Expecter) Find(ctx interface{}, filter interface{}, opts ...interface{}) *MongoClientCollectionPort_Find_Call {
	return &MongoClientCollectionPort_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MongoClientCollectionPort_Find_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOptions)) *MongoClientCollectionPort_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.FindOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.FindOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoClientCollectionPort_Find_Call) Return(_a0 *mongo.Cursor, _a1 error) *MongoClientCollectionPort_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoClientCollectionPort_Find_Call) RunAndReturn(run func(context.Context, interface{}, ...*options.FindOptions) (*mongo.Cursor, error)) *MongoClientCollectionPort_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, filter, opts
func (_m *MongoClientCollectionPort) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) *mongo.SingleResult {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *mongo.SingleResult
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOneOptions) *mongo.SingleResult); ok {
		r0 = rf(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}

	return r0
}

// MongoClientCollectionPort_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MongoClientCollectionPort_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOneOptions
func (_e *MongoClientCollectionPort_Expecter) FindOne(ctx interface{}, filter interface{}, opts ...interface{}) *MongoClientCollectionPort_FindOne_Call {
	return &MongoClientCollectionPort_FindOne_Call{Call: _e.mock.On("FindOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MongoClientCollectionPort_FindOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions)) *MongoClientCollectionPort_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.FindOneOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.FindOneOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoClientCollectionPort_FindOne_Call) Return(_a0 *mongo.SingleResult) *MongoClientCollectionPort_FindOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MongoClientCollectionPort_FindOne_Call) RunAndReturn(run func(context.Context, interface{}, ...*options.FindOneOptions) *mongo.SingleResult) *MongoClientCollectionPort_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function with given fields: ctx, document, opts
func (_m *MongoClientCollectionPort) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, document)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.InsertOneOptions) (*mongo.InsertOneResult, error)); ok {
		return rf(ctx, document, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.InsertOneOptions) *mongo.InsertOneResult); ok {
		r0 = rf(ctx, document, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.InsertOneOptions) error); ok {
		r1 = rf(ctx, document, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoClientCollectionPort_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type MongoClientCollectionPort_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - document interface{}
//   - opts ...*options.InsertOneOptions
func (_e *MongoClientCollectionPort_Expecter) InsertOne(ctx interface{}, document interface{}, opts ...interface{}) *MongoClientCollectionPort_InsertOne_Call {
	return &MongoClientCollectionPort_InsertOne_Call{Call: _e.mock.On("InsertOne",
		append([]interface{}{ctx, document}, opts...)...)}
}

func (_c *MongoClientCollectionPort_InsertOne_Call) Run(run func(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions)) *MongoClientCollectionPort_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.InsertOneOptions, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*options.InsertOneOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoClientCollectionPort_InsertOne_Call) Return(_a0 *mongo.InsertOneResult, _a1 error) *MongoClientCollectionPort_InsertOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoClientCollectionPort_InsertOne_Call) RunAndReturn(run func(context.Context, interface{}, ...*options.InsertOneOptions) (*mongo.InsertOneResult, error)) *MongoClientCollectionPort_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function with given fields: ctx, filter, update, opts
func (_m *MongoClientCollectionPort) UpdateOne(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter, update)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) (*mongo.UpdateResult, error)); ok {
		return rf(ctx, filter, update, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) *mongo.UpdateResult); ok {
		r0 = rf(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) error); ok {
		r1 = rf(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MongoClientCollectionPort_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type MongoClientCollectionPort_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - opts ...*options.UpdateOptions
func (_e *MongoClientCollectionPort_Expecter) UpdateOne(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MongoClientCollectionPort_UpdateOne_Call {
	return &MongoClientCollectionPort_UpdateOne_Call{Call: _e.mock.On("UpdateOne",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MongoClientCollectionPort_UpdateOne_Call) Run(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions)) *MongoClientCollectionPort_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.UpdateOptions, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(*options.UpdateOptions)
			}
		}
		run(args[0].(context.Context), args[1].(interface{}), args[2].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MongoClientCollectionPort_UpdateOne_Call) Return(_a0 *mongo.UpdateResult, _a1 error) *MongoClientCollectionPort_UpdateOne_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MongoClientCollectionPort_UpdateOne_Call) RunAndReturn(run func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) (*mongo.UpdateResult, error)) *MongoClientCollectionPort_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewMongoClientCollectionPort creates a new instance of MongoClientCollectionPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongoClientCollectionPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongoClientCollectionPort {
	mock := &MongoClientCollectionPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
